test script - determine kibana plugin version

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -41,6 +41,26 @@ workflow:
       when: never
     - when: always
 
+determine_kibana_plugin_version_test:
+  stage: build
+  script:
+    - |
+      ES_VERSION=7.17.7
+      SG_VERSION=1.0.0
+      KIBANA_VERSION=$(git ls-remote --tags --sort=-v:refname https://gitlab-ci-token:${CI_JOB_TOKEN}@git.floragunn.com/search-guard/search-guard-kibana-plugin "sg-flx-*-$ES_VERSION" | head --lines=1 | cut --delimiter='/' --fields=3 | sed -n 's/^sg-flx-\(.*\)$/\1/p')
+      if [ -z "$KIBANA_VERSION" ]; then
+        echo "Cannot find compatible version of kibana plugin (ES v$ES_VERSION). Is it already deployed?"
+        exit 1
+      else
+        echo "Found compatible version of kibana plugin: $KIBANA_VERSION"
+      fi
+      mvn $MAVEN_CLI_OPTS -DskipTests -Delasticsearch.version=$ES_VERSION -Dsg-suite.version=$SG_VERSION -Dsg-kibana-plugin.version=$KIBANA_VERSION clean install || exit 1
+  artifacts:
+    when: on_success
+    paths:
+      - "*/target"
+    expire_in: 10m
+
 upload_mvn_third_party_deps:
   allow_failure: false
   stage: prepare
