test

diff --git a/ci/frontend-int-tests.yml b/ci/frontend-int-tests.yml
--- a/ci/frontend-int-tests.yml
+++ b/ci/frontend-int-tests.yml
@@ -48,7 +48,24 @@ check_frontend_prerequisites:
       echo "PLUGIN_ARIFACT_URL=$PLUGIN_ARIFACT_URL" >> frontend-int-test.env
       echo "CHECK_FRONTEND_PREREQUISITES=1" >> frontend-int-test.env  
 
-      
+
+failed_frontend_prerequisites:
+  allow_failure: true
+  tags:
+    - test
+  stage: "Frontend Int Tests"
+  image: "$SG_BUILD_IMAGE"
+  needs:
+    - job: build
+  rules:
+    - if: '$CHECK_FRONTEND_PREREQUISITES != "1"'
+      when: always       
+  script:
+    - |
+  script:
+    - |
+      echo "ERROR: check_frontend_prerequisites finished with errors, check job log for more details"
+      exit 1
 
 frontend_int_tests:
   allow_failure: false
@@ -56,7 +73,8 @@ frontend_int_tests:
   rules:
     - if: '$DOCKER_ONLY || $CI_COMMIT_MESSAGE =~ /.*SKIP-UT.*/ || $CI_COMMIT_MESSAGE =~ /.*SKIP-TESTS.*/'
       when: never    
-    - when: on_success     
+    - if: '$CHECK_FRONTEND_PREREQUISITES == "1"'
+      when: always
   needs:
     - job: check_frontend_prerequisites
       artifacts: true
@@ -66,11 +84,11 @@ frontend_int_tests:
   trigger:
     strategy: depend
     include:
-      - local: ci/frontend-int-check.yml
       - project: search-guard/search-guard-kibana-plugin
         ref: ${SG_KI_BRANCH}
         file: ".gitlab-ci-branch-specific.yml"
-      # - project: search-guard/search-guard-kibana-plugin
-      #   ref: ${SG_KI_BRANCH}
-      #   file: "ci/frontend-int-tests.yml"
+      - project: search-guard/search-guard-kibana-plugin
+        ref: ${SG_KI_BRANCH}
+        file: "ci/frontend-int-tests.yml"
+
       
