test

diff --git a/ci/frontend-int-tests.yml b/ci/frontend-int-tests.yml
--- a/ci/frontend-int-tests.yml
+++ b/ci/frontend-int-tests.yml
@@ -49,25 +49,25 @@ check_frontend_prerequisites:
       echo "CHECK_FRONTEND_PREREQUISITES=1" >> frontend-int-test.env  
 
 
-failed_frontend_prerequisites:
-  allow_failure: true
-  tags:
-    - test
-  stage: "Frontend Int Tests"
-  image: "$SG_BUILD_IMAGE"
-  needs:
-    - job: build
-    - job: check_frontend_prerequisites
-      artifacts: true
-  rules:
-    - if: '$CHECK_FRONTEND_PREREQUISITES != "1"'
-      when: always       
-  script:
-    - |
-  script:
-    - |
-      echo "ERROR: check_frontend_prerequisites finished with errors, check job log for more details"
-      exit 1
+# failed_frontend_prerequisites:
+#   allow_failure: true
+#   tags:
+#     - test
+#   stage: "Frontend Int Tests"
+#   image: "$SG_BUILD_IMAGE"
+#   needs:
+#     - job: build
+#     - job: check_frontend_prerequisites
+#       artifacts: true
+#   rules:
+#     - if: '$CHECK_FRONTEND_PREREQUISITES != "1"'
+#       when: always       
+#   script:
+#     - |
+#   script:
+#     - |
+#       echo "ERROR: check_frontend_prerequisites finished with errors, check job log for more details"
+#       exit 1
 
 frontend_int_tests:
   allow_failure: false
@@ -75,8 +75,6 @@ frontend_int_tests:
   rules:
     - if: '$DOCKER_ONLY || $CI_COMMIT_MESSAGE =~ /.*SKIP-UT.*/ || $CI_COMMIT_MESSAGE =~ /.*SKIP-TESTS.*/'
       when: never    
-    - if: '$CHECK_FRONTEND_PREREQUISITES == "1"'
-      when: always
   needs:
     - job: build
     - job: check_frontend_prerequisites
@@ -84,6 +82,8 @@ frontend_int_tests:
   variables:
     SG_ES_PLUGIN: ${PLUGIN_ARIFACT_URL}
     SG_KI_PLUGIN: ${KIBANA_ARIFACT_URL}
+    CHECK_JOB_NAME: "check_frontend_prerequisites"
+    PARENT_PIPELINE_PREREQUISITES: ${CHECK_FRONTEND_PREREQUISITES}
   trigger:
     strategy: depend
     include:
