test

diff --git a/ci/frontend-int-tests.yml b/ci/frontend-int-tests.yml
--- a/ci/frontend-int-tests.yml
+++ b/ci/frontend-int-tests.yml
@@ -49,24 +49,24 @@ check_frontend_prerequisites:
       echo "CHECK_FRONTEND_PREREQUISITES=1" >> frontend-int-test.env  
 
 
-failed_frontend_prerequisites:
-  allow_failure: true
-  tags:
-    - test
-  stage: "Frontend Int Tests"
-  image: "$SG_BUILD_IMAGE"
-  needs:
-    - job: check_frontend_prerequisites
-      artifacts: true
-  rules:
-    - if: '$CHECK_FRONTEND_PREREQUISITES != "1"'
-      when: always       
-  script:
-    - |
-  script:
-    - |
-      echo "ERROR: check_frontend_prerequisites finished with errors, check job log for more details"
-      exit 1
+# failed_frontend_prerequisites:
+#   allow_failure: true
+#   tags:
+#     - test
+#   stage: "Frontend Int Tests"
+#   image: "$SG_BUILD_IMAGE"
+#   needs:
+#     - job: check_frontend_prerequisites
+#       artifacts: true
+#   rules:
+#     - if: '$CHECK_FRONTEND_PREREQUISITES != "1"'
+#       when: always       
+#   script:
+#     - |
+#   script:
+#     - |
+#       echo "ERROR: check_frontend_prerequisites finished with errors, check job log for more details"
+#       exit 1
 
 frontend_int_tests:
   allow_failure: false
