Adapt autopackager

diff --git a/ci/veracode-scan.yml b/ci/veracode-scan.yml
--- a/ci/veracode-scan.yml
+++ b/ci/veracode-scan.yml
@@ -38,8 +38,16 @@ veracode_auto_packager_build:
     - veracode-scan
   script:
     - | 
+      echo "Install Veracode CLI"
       curl -fsS https://tools.veracode.com/veracode-cli/install | VERACODE_CLI_VERSION=$VERACODE_CLI_VERSION  sh
-      ./veracode package -t directory -s .  -a -o veracode-output
+      ./veracode version
+      echo "Execute Veracode auto-packager"
+      output=$(./veracode package -t directory -s . -a -o veracode-output)
+      echo "$output"
+      if echo "$output" | grep -iqE "Build failed|build/install failed"; then
+          echo "Error: Build failed detected in the output."
+          exit 1
+      fi
   artifacts:
     when: on_success
     expire_in: 12h
